"""UniTime AI Ingestion Gateway - Agent State Definitions.

Defines the LangGraph-compatible state container for managing curriculum
ingestion workflows, slice iterations, validation checkpoints,
human-in-the-loop interactions, and persistent audit histories.
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict
from langgraph.graph.message import add_messages

# Canonical status definitions for the ingestion agent workflow
STATUS_PROCESSING: Literal["processing"] = "processing"
STATUS_WAITING_FOR_HUMAN: Literal["waiting_for_human"] = "waiting_for_human"
STATUS_COMPLETED: Literal["completed"] = "completed"
STATUS_ERROR: Literal["error"] = "error"

AgentStatus = Literal["processing", "waiting_for_human", "completed", "error"]


class IngestAgentState(TypedDict):
    """Execution state schema for the UniTime smart ingestion LangGraph agent.

    This state container tracks the end-to-end lifecycle of a curriculum document
    from raw input slicing, chunk-by-chunk LLM extraction, schema & semantic validation,
    human-in-the-loop ambiguity resolution, up to UniTime server persistence.

    Attributes:
        document_path: Absolute or relative file path to the source document being ingested.
        document_type: Document format classification (e.g., 'pdf', 'excel', 'table', 'text', 'auto').
        slices: List of chunk metadata and text representations generated by DocumentSlicer.
        current_slice_index: Zero-based pointer to the current slice being processed.
        partial_payloads: List of partial curriculum JSON objects extracted per slice.
        unified_payload: Consolidated smart-ingest JSON payload ready for validation/ingest.
        validation_result: Detailed schema and semantic validation outcome dictionary.
        memory_context: Active department quirks, room aliases, and instructor habits loaded from memory.
        ambiguities: Unresolved conflicts, ambiguous identities, or questions requiring user input.
        human_response: User feedback or choice provided during workflow interrupt.
        audit_logs: Chronological list of reasoning events, automatic fixes, and warning entries.
        ingest_result: Execution result and summary returned from UniTime server API.
        status: Current pipeline execution phase ('processing', 'waiting_for_human', 'completed', 'error').
        messages: LangGraph message history reducer used for ReAct chat reasoning and tool execution.
    """

    document_path: str
    document_type: str
    slices: List[Dict[str, Any]]
    current_slice_index: int
    partial_payloads: List[Dict[str, Any]]
    unified_payload: Optional[Dict[str, Any]]
    validation_result: Optional[Dict[str, Any]]
    memory_context: Dict[str, Any]
    ambiguities: List[Dict[str, Any]]
    human_response: Optional[Any]
    audit_logs: List[Dict[str, Any]]
    ingest_result: Optional[Dict[str, Any]]
    status: str
    messages: Annotated[List[Any], add_messages]


def create_initial_state(
    document_path: str,
    document_type: str = "auto",
    memory_context: Optional[Dict[str, Any]] = None,
    initial_messages: Optional[List[Any]] = None,
) -> IngestAgentState:
    """Initialize a clean IngestAgentState instance with standard defaults.

    Args:
        document_path: Path to the curriculum document to process.
        document_type: Document format category (defaults to 'auto').
        memory_context: Optional initial department memory or quirks context.
        initial_messages: Optional starting conversation/prompt messages.

    Returns:
        A fully populated IngestAgentState dictionary.
    """
    return IngestAgentState(
        document_path=str(document_path),
        document_type=str(document_type),
        slices=[],
        current_slice_index=0,
        partial_payloads=[],
        unified_payload=None,
        validation_result=None,
        memory_context=dict(memory_context) if memory_context else {},
        ambiguities=[],
        human_response=None,
        audit_logs=[],
        ingest_result=None,
        status=STATUS_PROCESSING,
        messages=list(initial_messages) if initial_messages else [],
    )
